version: "3.3"

services:
  ldap:
    # https://github.com/bitnami/containers/tree/main/bitnami/openldap#readme
    image: bitnami/openldap:latest
    platform: linux
    environment:
     - LDAP_USERS=user01,user02,nobody
     - LDAP_PASSWORDS=password,password,password
    logging:
      options:
         tag: "ldap"
    networks:
     - back

  idp:
    image: test-idp:latest
    build: src/idp
    logging:
      options:
         tag: "idp"
    networks:
     - front
     - back
    ports:
     - "8443:443"

  aws:
    image: motoserver/moto:4.1.4
    environment:
     # Enable IAM. If not set everything is permitted.
     - INITIAL_NO_AUTH_ACTION_COUNT=0
    logging:
      options:
         tag: "idp"
    networks:
     - front
     - back
    ports:
     - "8443:443"

networks:
  front:
  back:
