#!/bin/bash

MD5OPTS="--quiet --strict"
MD5SUMS="cache/MD5SUM .tox/MD5SUM"

if python scripts/weekold.py cache/* && md5sum $MD5OPTS -c $MD5SUMS <&-
then
    echo "Touching cache and tox env so make will not rebuild them."
    touch -c cache .tox/wheel/pyvenv.cfg

    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#using-workflow-commands-to-access-toolkit-functions
    echo "::set-output name=invalid::False"
else
    echo "Forcing rebuild of tox virtualenv(s)."
    rm -rf .tox cache

    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#using-workflow-commands-to-access-toolkit-functions
    echo "::set-output name=invalid::True"
fi
